import type { CatalogItem, SourceRecord } from "./types";

export const SOURCE_SEED: Omit<SourceRecord, "lastIngestAt">[] = [
  {
    id: "src_dfir",
    name: "The DFIR Report",
    slug: "dfir",
    category: "incident_response",
    priority: 1,
    homepageUrl: "https://thedfirreport.com/reports/",
    feedUrl: "https://thedfirreport.com/feed/",
    enabled: true,
    trustLevel: "high",
    notes: "Stage-by-stage real intrusion timelines. Primary chain source.",
  },
  {
    id: "src_unit42",
    name: "Unit 42",
    slug: "unit42",
    category: "threat_research",
    priority: 1,
    homepageUrl: "https://unit42.paloaltonetworks.com/",
    feedUrl: "https://unit42.paloaltonetworks.com/feed/",
    enabled: true,
    trustLevel: "high",
    notes: "Technical attack-chain investigations with ATT&CK tables.",
  },
  {
    id: "src_sentinel",
    name: "SentinelLABS",
    slug: "sentinellabs",
    category: "malware_research",
    priority: 1,
    homepageUrl: "https://www.sentinelone.com/labs/",
    feedUrl: "https://www.sentinelone.com/labs/feed/",
    enabled: true,
    trustLevel: "high",
    notes: "Deep malware and TTP technical analysis.",
  },
  {
    id: "src_huntress",
    name: "Huntress",
    slug: "huntress",
    category: "incident_response",
    priority: 2,
    homepageUrl: "https://www.huntress.com/blog",
    feedUrl: "https://www.huntress.com/blog/rss.xml",
    enabled: true,
    trustLevel: "high",
    notes: "Enterprise intrusion timelines from SOC cases.",
  },
  {
    id: "src_mandiant",
    name: "Google Threat Intelligence",
    slug: "mandiant",
    category: "threat_intelligence",
    priority: 2,
    homepageUrl: "https://cloud.google.com/blog/topics/threat-intelligence",
    feedUrl: "https://cloud.google.com/feeds/threat-intelligence.xml",
    enabled: true,
    trustLevel: "official",
    notes: "Full adversary operations and ransomware TTP studies.",
  },
  {
    id: "src_msft",
    name: "Microsoft Threat Intelligence",
    slug: "microsoft",
    category: "threat_intelligence",
    priority: 2,
    homepageUrl: "https://www.microsoft.com/en-us/security/blog/topic/threat-intelligence/",
    feedUrl: "https://www.microsoft.com/en-us/security/blog/feed/",
    enabled: true,
    trustLevel: "official",
    notes: "Windows, AD, Entra, and cloud intrusion research.",
  },
  {
    id: "src_talos",
    name: "Cisco Talos",
    slug: "talos",
    category: "threat_research",
    priority: 3,
    homepageUrl: "https://blog.talosintelligence.com/",
    feedUrl: "https://blog.talosintelligence.com/rss/",
    enabled: true,
    trustLevel: "high",
    notes: "Malware, campaign, and IR engagement write-ups.",
  },
  {
    id: "src_cisa",
    name: "CISA Advisories",
    slug: "cisa",
    category: "advisory",
    priority: 2,
    homepageUrl: "https://www.cisa.gov/news-events/cybersecurity-advisories",
    feedUrl: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    enabled: true,
    trustLevel: "official",
    notes: "Government alerts, #StopRansomware, and observed TTPs.",
  },
  {
    id: "src_mitre",
    name: "MITRE ATT&CK",
    slug: "mitre",
    category: "mitre_research",
    priority: 1,
    homepageUrl: "https://medium.com/mitre-attack",
    feedUrl: "https://medium.com/feed/mitre-attack",
    enabled: true,
    trustLevel: "official",
    notes: "Technique research and adversary emulation notes from ATT&CK.",
  },
  {
    id: "src_elastic",
    name: "Elastic Security Labs",
    slug: "elastic",
    category: "threat_research",
    priority: 2,
    homepageUrl: "https://www.elastic.co/security-labs",
    feedUrl: "https://www.elastic.co/security-labs/rss/feed.xml",
    enabled: true,
    trustLevel: "high",
    notes: "Malware, campaign, and detection-engineering write-ups.",
  },
  {
    id: "src_specterops",
    name: "SpecterOps",
    slug: "specterops",
    category: "adversary_emulation",
    priority: 2,
    homepageUrl: "https://posts.specterops.io/",
    feedUrl: "https://posts.specterops.io/feed",
    enabled: true,
    trustLevel: "high",
    notes: "Adversary tradecraft, BloodHound, and purple-team research.",
  },
  {
    id: "src_bleeping",
    name: "BleepingComputer Research",
    slug: "bleepingcomputer",
    category: "threat_intelligence",
    priority: 2,
    homepageUrl: "https://www.bleepingcomputer.com/",
    feedUrl: "https://www.bleepingcomputer.com/feed/",
    enabled: true,
    trustLevel: "reputable",
    notes: "Ransomware outbreaks, zero-day alerts, and malware analyses.",
  },
  {
    id: "src_trendmicro",
    name: "Trend Micro Research",
    slug: "trendmicro",
    category: "threat_research",
    priority: 2,
    homepageUrl: "https://www.trendmicro.com/en_us/research.html",
    feedUrl: "https://feeds.feedburner.com/TrendMicroResearch",
    enabled: true,
    trustLevel: "high",
    notes: "Deep threat investigations, APT campaigns, and loader writeups.",
  },
  {
    id: "src_ahnlab",
    name: "AhnLab ASEC",
    slug: "ahnlab",
    category: "malware_research",
    priority: 2,
    homepageUrl: "https://asec.ahnlab.com/en/",
    feedUrl: "https://asec.ahnlab.com/en/feed/",
    enabled: true,
    trustLevel: "high",
    notes: "Active malware analysis, infostealers, and ransomware triage.",
  },
  {
    id: "src_checkpoint",
    name: "Check Point Research",
    slug: "checkpoint",
    category: "threat_research",
    priority: 2,
    homepageUrl: "https://research.checkpoint.com/",
    feedUrl: "https://research.checkpoint.com/feed/",
    enabled: true,
    trustLevel: "high",
    notes: "Nation-state APT reports and reverse engineering analyses.",
  },
  {
    id: "src_sans",
    name: "SANS Internet Storm Center",
    slug: "sans",
    category: "incident_response",
    priority: 2,
    homepageUrl: "https://isc.sans.edu/",
    feedUrl: "https://isc.sans.edu/rssfeed.xml",
    enabled: true,
    trustLevel: "official",
    notes: "Daily intrusion telemetry, zero-day exploitation, and packet analysis.",
  },
  {
    id: "src_sophos",
    name: "Sophos X-Ops",
    slug: "sophos",
    category: "threat_research",
    priority: 2,
    homepageUrl: "https://news.sophos.com/en-us/category/threat-research/",
    feedUrl: "https://news.sophos.com/en-us/category/threat-research/feed/",
    enabled: true,
    trustLevel: "high",
    notes: "Ransomware negotiations, attacker toolkits, and root-cause analyses.",
  },
  {
    id: "src_redcanary",
    name: "Red Canary Intelligence",
    slug: "redcanary",
    category: "incident_response",
    priority: 2,
    homepageUrl: "https://redcanary.com/blog/",
    feedUrl: "https://redcanary.com/blog/feed/",
    enabled: true,
    trustLevel: "high",
    notes: "Threat detection guidance, sub-technique procedures, and intelligence.",
  },
  {
    id: "src_sekoia",
    name: "Sekoia.io CTI",
    slug: "sekoia",
    category: "threat_intelligence",
    priority: 2,
    homepageUrl: "https://blog.sekoia.io/",
    feedUrl: "https://blog.sekoia.io/feed/",
    enabled: true,
    trustLevel: "high",
    notes: "Adversary tracking, infrastructure mapping, and technical reports.",
  },
  {
    id: "src_eset",
    name: "WeLiveSecurity (ESET)",
    slug: "eset",
    category: "threat_research",
    priority: 2,
    homepageUrl: "https://www.welivesecurity.com/en/",
    feedUrl: "https://www.welivesecurity.com/en/rss/feed/",
    enabled: true,
    trustLevel: "high",
    notes: "European APT tracking, sophisticated malware reverse engineering.",
  },
  {
    id: "src_rapid7",
    name: "Rapid7 Research",
    slug: "rapid7",
    category: "threat_research",
    priority: 2,
    homepageUrl: "https://www.rapid7.com/blog/tag/threat-intel/",
    feedUrl: "https://www.rapid7.com/blog/tag/threat-intel/feed/",
    enabled: true,
    trustLevel: "high",
    notes: "Mass exploitation vulnerability write-ups and incident response findings.",
  },
];

export const REPORT_CATALOG: CatalogItem[] = [
  {
    id: "cat_dfir_akira",
    sourceSlug: "dfir",
    title: "From Bing Search to Ransomware: Bumblebee and AdaptixC2 Deliver Akira",
    url: "https://thedfirreport.com/2026/06/29/from-bing-search-to-ransomware-bumblebee-and-adaptixc2-deliver-akira-3/",
    published: "2026-06-29",
    why: "SEO poisoning → loader → credential theft → lateral movement → ransomware.",
  },
  {
    id: "cat_dfir_lockbit",
    sourceSlug: "dfir",
    title: "Apache ActiveMQ Exploit Leads to LockBit Ransomware",
    url: "https://thedfirreport.com/2026/02/23/apache-activemq-exploit-leads-to-lockbit-ransomware/",
    published: "2026-02-23",
    why: "Public exploit to full domain encryption. Strong ordered chain.",
  },
  {
    id: "cat_dfir_lynx",
    sourceSlug: "dfir",
    title: "Cat’s Got Your Files: Lynx Ransomware",
    url: "https://thedfirreport.com/2025/12/17/cats-got-your-files-lynx-ransomware/",
    published: "2025-12-17",
    why: "Valid RDP credentials, no brute force — identity-first initial access.",
  },
  {
    id: "cat_unit42_ttps",
    sourceSlug: "unit42",
    title: "Ransomware Tactics, Techniques, and Procedures in a Shifting Threat Landscape",
    url: "https://cloud.google.com/blog/topics/threat-intelligence/ransomware-ttps-shifting-threat-landscape",
    published: "2026-03-16",
    why: "Mandiant IR stats: stolen credentials and RDP lateral movement at scale.",
  },
  {
    id: "cat_msft_trust",
    sourceSlug: "microsoft",
    title: "Undermining the trust boundary: third-party compromise intrusion",
    url: "https://www.microsoft.com/en-us/security/blog/2026/05/12/undermining-the-trust-boundary-investigating-a-stealthy-intrusion-through-third-party-compromise/",
    published: "2026-05-12",
    why: "Credential interception, tunnels, RDP lateral movement through a trusted MSP.",
  },
  {
    id: "cat_cisa_stop",
    sourceSlug: "cisa",
    title: "#StopRansomware Guide",
    url: "https://www.cisa.gov/stopransomware/ransomware-guide",
    published: "2026-06-23",
    why: "Official prevention and response baseline for simulation planning.",
  },
];
