/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as LibraryReportIdRouteImport } from './routes/library.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryReportIdRoute = LibraryReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingest': typeof IngestRoute
  '/library': typeof LibraryRouteWithChildren
  '/sources': typeof SourcesRoute
  '/library/$reportId': typeof LibraryReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingest': typeof IngestRoute
  '/library': typeof LibraryRouteWithChildren
  '/sources': typeof SourcesRoute
  '/library/$reportId': typeof LibraryReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingest': typeof IngestRoute
  '/library': typeof LibraryRouteWithChildren
  '/sources': typeof SourcesRoute
  '/library/$reportId': typeof LibraryReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ingest' | '/library' | '/sources' | '/library/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ingest' | '/library' | '/sources' | '/library/$reportId'
  id:
    | '__root__'
    | '/'
    | '/ingest'
    | '/library'
    | '/sources'
    | '/library/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngestRoute: typeof IngestRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$reportId': {
      id: '/library/$reportId'
      path: '/$reportId'
      fullPath: '/library/$reportId'
      preLoaderRoute: typeof LibraryReportIdRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryReportIdRoute: typeof LibraryReportIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryReportIdRoute: LibraryReportIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngestRoute: IngestRoute,
  LibraryRoute: LibraryRouteWithChildren,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
